server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/qa_homework_db
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    locations: classpath:db/migration,classpath:qa/db/migration