server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/homework_db
    username: postgres
    password: postgres
  profiles:
    active: dev

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: BackEnd Project
