server:
  port: 8898

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dev_homework_db
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect